
server:
  port: 8070

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # DDL 출력
    
  datasource:
    username: test
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test

jwt:
  header: Authorization
  secret: 123
  access-token-time: 900

---
server:
    port: 9000

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/LIFE_SHARE?serverTimezone=UTC&characterEncoding=UTF-8


---
server:
    port: 8080

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/LIFE_SHARE?serverTimezone=UTC&characterEncoding=UTF-8

      