version: "3"

services: 
  db:
    image: db2b37ec6181
    container_name: jason-mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "1230"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - D:/docker/mysql/data:/var/lib/mysql