server:
  port: 8090    # 기본 포트 설정

spring:
  # config:
  #   activate:
  #     on-profile: local

  datasource:
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/LIFE_SHARE?serverTimezone=UTC&characterEncoding=UTF-8

---
server:
    port: 9000

spring:
  config:
    activate:
      on-profile: dev


---
server:
    port: 8080

spring:
  config:
    activate:
      on-profile: prod

      